#name, main, version and api are required
name: WorldEditor
main: plugin\WorldEditor
version: "1.1"
api: 1.0.0

author: 우유맛비누
commands:
 /pos1:
  usage: false
  permission: worldedit.command.setpos1
 /pos2:
  usage: false
  permission: worldedit.command.setpos2
 /set:
  usage: false
  permission: worldedit.command.setblock
 /replace:
  usage: false
  permission: worldedit.command.replaceblock
 /undo:
  usage: false
  permission: worldedit.command.undoblock
 /redo:
  usage: false
  permission: worldedit.command.redoblock
 /copy:
  usage: false
  permission: worldedit.command.copyblock
 /paste:
  usage: false
  permission: worldedit.command.pasteblock
 /cut:
  usage: false
  permission: worldedit.command.cutblock
 

permissions:
 worldedit.command.*:
  default: op
  description: false