#name, main, version and api are required
name: WorldEditor
main: leinne\worldeditor\WorldEditor
version: 2.0.0
api: ["4.0.0"]

author: SW승원
commands:
 /wand:
  usage: ""
  permission: worldeditor.command.givewand
 /pos1:
  usage: ""
  permission: worldeditor.command.setpos
 /pos2:
  usage: ""
  permission: worldeditor.command.setpos
 /set:
  usage: ""
  permission: worldeditor.command.setblock
 /replace:
  usage: ""
  permission: worldeditor.command.replaceblock
 /undo:
  usage: ""
  permission: worldeditor.command.undoblock
 /redo:
  usage: ""
  permission: worldeditor.command.redoblock
 /copy:
  usage: ""
  permission: worldeditor.command.copyblock
 /paste:
  usage: ""
  permission: worldeditor.command.pasteblock
 /cut:
  usage: ""
  permission: worldeditor.command.cutblock
permissions:
 worldeditor.command.*:
  default: op